sbl-s1: Add sbl-s1 sources
This commit imports mcom03-hwinit [1] sources to implement sbl-s1
boot stage firmware from commit 0d03895e742d338a1e982de8b5bb55edd073ac6b
with modification:

* Build system is now based on cmake.
* TRNG driver is removed.
* -lgcc ld flag is used instead of building __udivdi3 from sources.
* Submodules are not used now.
* Filename underscores are replaced with hyphen.
* All drivers are moved in common dir.

Also it adds rules for pre-commit cppcheck and clang-format hooks to
fix wrong detection of "for" operator in asm header comment:

sbl-s1/include/asm.h:163:54: error: syntax error [syntaxError]
        addi $sp, -CONTEXT_WORDS*4  # Allocate space for registers

[1] https://git.elvees.com/TrustLab-Engineers-Internal/hwinit

Issue: #MCOM03SW-2154
Change-Id: I950466a5a185066a186096f2f285723662f2b57f